
MagicEightBallGateway:
  scopes: hybris.magiceightball_read
  magicEightBallUrl: https://magiceightball.cfapps.us10.hana.ondemand.com/MagicEightBall/
  oauth2:
    tokenUrl: https://api.yaas.io/hybris/oauth2/v1/token
    client:
      id: OzmPuyjgvudY6yYklA4z4xUf0XkxFYrt
      secret: UI5R8abdzUn0qjaR
  basicAuth:
    username: username
    password: Password1

---
#HCP
spring:
  profiles: development

MagicEightBallGateway:
  scopes: NA
  magicEightBallUrl: https://magiceightball.cfapps.us10.hana.ondemand.com/
  oauth2:
    tokenUrl: NA
    client:
      id: NA
      secret: NA
  basicAuth:
    username: username
    password: Password1

---
#Yaas
spring:
    profiles: integration

MagicEightBallGateway:
  scopes: hybris.magiceightball_read
  magicEightBallUrl: https://api.yaas.io/fdl/magiceightball/v1/MagicEightBall/
  oauth2:
    tokenUrl: https://api.yaas.io/hybris/oauth2/v1/token
    client:
      id: OzmPuyjgvudY6yYklA4z4xUf0XkxFYrt
      secret: UI5R8abdzUn0qjaR
  basicAuth:
    username: username
    password: Password1


---
# eureka
spring:
  profiles: production

MagicEightBallGateway:
  scopes: NA
  magicEightBallUrl: http://magiceightball//MagicEightBall
  oauth2:
    tokenUrl: NA
    client:
      id: NA
      secret: NA
  basicAuth:
    username: username
    password: Password1

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka:Password1@eureka-server.cfapps.us10.hana.ondemand.com/eureka


